In [2]:
import pandas as pd

In [3]:
tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

In [4]:
tips

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [5]:
tips.shape

(244, 8)

In [6]:
tips.describe(include='all')

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size
count,244.000000,244.000000,244.000000,244,244,244,244,244.000000
unique,NaN,NaN,NaN,2,2,4,2,NaN
top,NaN,NaN,NaN,Male,No,Sat,Dinner,NaN
freq,NaN,NaN,NaN,157,151,87,176,NaN
mean,121.500000,19.785943,2.998279,NaN,NaN,NaN,NaN,2.569672
std,70.580923,8.902412,1.383638,NaN,NaN,NaN,NaN,0.951100
min,0.000000,3.070000,1.000000,NaN,NaN,NaN,NaN,1.000000
25%,60.750000,13.347500,2.000000,NaN,NaN,NaN,NaN,2.000000
50%,121.500000,17.795000,2.900000,NaN,NaN,NaN,NaN,2.000000
75%,182.250000,24.127500,3.562500,NaN,NaN,NaN,NaN,3.000000
max,243.000000,50.810000,10.000000,NaN,NaN,NaN,NaN,6.000000

In [7]:
tips.describe(include=object)

C:\Users\ashut\AppData\Local\Temp\ipykernel_15432\2944691910.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  tips.describe(include=object)

         sex smoker  day    time
count    244    244  244     244
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [8]:
tips.shape

(244, 8)

In [9]:
tips['day'].unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [10]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv' \
'')

In [11]:
titanic.shape

(1309, 11)

In [12]:
# var.shape
#

In [13]:
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

In [14]:
wine_quality.shape

(6497, 13)

In [15]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [16]:
amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

In [17]:
amazon['mes'].unique()

<StringArray>
[  'Janeiro', 'Fevereiro',     'Março',     'Abril',      'Maio',     'Junho',
     'Julho',    'Agosto',  'Setembro',   'Outubro',  'Novembro',  'Dezembro']
Length: 12, dtype: str

In [18]:
amazon.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [19]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [20]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [21]:
hr['department'].unique()

<StringArray>
[      'sales',  'accounting',          'hr',   'technical',     'support',
  'management',          'IT', 'product_mng',   'marketing',       'RandD']
Length: 10, dtype: str

In [22]:
# var['col_name'].value_counts()

In [23]:
hr['department'].value_counts()

department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [24]:
tips['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [25]:
hr['department'].value_counts()

department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [26]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [27]:
tips['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [28]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [29]:
wine_quality['type'].value_counts()

type
white    4898
red      1599
Name: count, dtype: int64

In [30]:
tips.columns

Index(['Unnamed: 0', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time',
       'size'],
      dtype='str')

In [31]:
amazon.columns

Index(['ano', 'mes', 'estado', 'numero', 'encontro'], dtype='str')

In [32]:
hr.columns

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='str')

In [33]:
tips.sample()

     Unnamed: 0  total_bill  tip     sex smoker   day    time  size
243         243       18.78  3.0  Female     No  Thur  Dinner     2

In [34]:
tips.sample(10)

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
71           71       17.07  3.00  Female     No   Sat  Dinner     3
8             8       15.04  1.96    Male     No   Sun  Dinner     2
39           39       31.27  5.00    Male     No   Sat  Dinner     3
231         231       15.69  3.00    Male    Yes   Sat  Dinner     3
190         190       15.69  1.50    Male    Yes   Sun  Dinner     2
149         149        7.51  2.00    Male     No  Thur   Lunch     2
128         128       11.38  2.00  Female     No  Thur   Lunch     2
115         115       17.31  3.50  Female     No   Sun  Dinner     2
16           16       10.33  1.67  Female     No   Sun  Dinner     3
174         174       16.82  4.00    Male    Yes   Sun  Dinner     2

In [35]:
tips.loc[0:5,['total_bill','sex','tip']]

   total_bill     sex   tip
0       16.99  Female  1.01
1       10.34    Male  1.66
2       21.01    Male  3.50
3       23.68    Male  3.31
4       24.59  Female  3.61
5       25.29    Male  4.71

In [36]:
tips.loc[[1,2,3,4]]

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [37]:
tips.iloc[1:5:1,2:6:1]

    tip     sex smoker  day
1  1.66    Male     No  Sun
2  3.50    Male     No  Sun
3  3.31    Male     No  Sun
4  3.61  Female     No  Sun

In [38]:
hr['number_project'].sum()

np.int64(57042)

In [39]:
hr['employee_id'].count()

np.int64(14999)

In [40]:
tips['tip'].mean()

np.float64(2.99827868852459)

In [41]:
tips['tip'].max()

np.float64(10.0)

In [42]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [43]:
hr['left'].sum()

np.int64(3571)

In [44]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [45]:
# Find the number of males in the tips
tips[tips['sex']=='Male']['sex'].count()

np.int64(157)

In [46]:
tips[(tips['sex']=='Female') & (tips['smoker']=='Yes')]['smoker'].count()

np.int64(33)

In [54]:
tips[(tips['day']=='Sun') & (tips['time']=='Lunch')]['Unnamed: 0'].count()

np.int64(0)

In [48]:
tips

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [52]:
tips[(tips['day']=="Sat") & (tips['time']=="Dinner")]['tip'].mean()

np.float64(2.993103448275862)

In [59]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [60]:
hr[(hr['department']=='sales') & (hr['salary']=='low')]['employee_id'].count()

np.int64(2099)

In [62]:
hr[hr['promotion_last_5years']>0]['employee_id'].count()

np.int64(319)

In [63]:
hr[hr['department']=='IT']['number_project'].mean()

np.float64(3.8166259168704157)