In [1]:
import pandas as pd

In [2]:
tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

In [3]:
tips

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [6]:
tips.shape

(244, 8)

In [8]:
tips.describe(include='all')

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size
count,244.000000,244.000000,244.000000,244,244,244,244,244.000000
unique,NaN,NaN,NaN,2,2,4,2,NaN
top,NaN,NaN,NaN,Male,No,Sat,Dinner,NaN
freq,NaN,NaN,NaN,157,151,87,176,NaN
mean,121.500000,19.785943,2.998279,NaN,NaN,NaN,NaN,2.569672
std,70.580923,8.902412,1.383638,NaN,NaN,NaN,NaN,0.951100
min,0.000000,3.070000,1.000000,NaN,NaN,NaN,NaN,1.000000
25%,60.750000,13.347500,2.000000,NaN,NaN,NaN,NaN,2.000000
50%,121.500000,17.795000,2.900000,NaN,NaN,NaN,NaN,2.000000
75%,182.250000,24.127500,3.562500,NaN,NaN,NaN,NaN,3.000000
max,243.000000,50.810000,10.000000,NaN,NaN,NaN,NaN,6.000000

In [9]:
tips.describe(include=object)

C:\Users\ashut\AppData\Local\Temp\ipykernel_4020\2944691910.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  tips.describe(include=object)

         sex smoker  day    time
count    244    244  244     244
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [10]:
tips.shape

(244, 8)

In [11]:
tips['day'].unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [12]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv' \
'')

In [13]:
titanic.shape

(1309, 11)

In [14]:
# var.shape
#

In [15]:
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

In [16]:
wine_quality.shape

(6497, 13)

In [17]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

In [19]:
amazon['mes'].unique()

<StringArray>
[  'Janeiro', 'Fevereiro',     'Março',     'Abril',      'Maio',     'Junho',
     'Julho',    'Agosto',  'Setembro',   'Outubro',  'Novembro',  'Dezembro']
Length: 12, dtype: str

In [21]:
amazon.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [22]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [24]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [25]:
hr['department'].unique()

<StringArray>
[      'sales',  'accounting',          'hr',   'technical',     'support',
  'management',          'IT', 'product_mng',   'marketing',       'RandD']
Length: 10, dtype: str

In [26]:
# var['col_name'].value_counts()

In [28]:
hr['department'].value_counts()

department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [29]:
tips['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [30]:
hr['department'].value_counts()

department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [34]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [35]:
tips['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [36]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [37]:
wine_quality['type'].value_counts()

type
white    4898
red      1599
Name: count, dtype: int64

In [38]:
tips.columns

Index(['Unnamed: 0', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time',
       'size'],
      dtype='str')

In [39]:
amazon.columns

Index(['ano', 'mes', 'estado', 'numero', 'encontro'], dtype='str')

In [40]:
hr.columns

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='str')

In [41]:
tips.sample()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [43]:
tips.sample(10)

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
125         125       29.80  4.20  Female     No  Thur   Lunch     6
235         235       10.07  1.25    Male     No   Sat  Dinner     2
38           38       18.69  2.31    Male     No   Sat  Dinner     3
142         142       41.19  5.00    Male     No  Thur   Lunch     5
40           40       16.04  2.24    Male     No   Sat  Dinner     3
191         191       19.81  4.19  Female    Yes  Thur   Lunch     2
119         119       24.08  2.92  Female     No  Thur   Lunch     4
129         129       22.82  2.18    Male     No  Thur   Lunch     3
12           12       15.42  1.57    Male     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3

In [46]:
tips.loc[0:5,['total_bill','sex','tip']]

   total_bill     sex   tip
0       16.99  Female  1.01
1       10.34    Male  1.66
2       21.01    Male  3.50
3       23.68    Male  3.31
4       24.59  Female  3.61
5       25.29    Male  4.71