In [1]:
import pandas as pd

In [20]:
cafe= pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/dirty_cafe_sales.csv')

In [21]:
cafe.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [4]:
cafe

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [22]:
cafe.duplicated().sum()

np.int64(0)

In [23]:
cafe['Transaction ID'].unique()

<StringArray>
['TXN_1961373', 'TXN_4977031', 'TXN_4271903', 'TXN_7034554', 'TXN_3160411',
 'TXN_2602893', 'TXN_4433211', 'TXN_6699534', 'TXN_4717867', 'TXN_2064365',
 ...
 'TXN_1538510', 'TXN_3897619', 'TXN_2739140', 'TXN_4766549', 'TXN_7851634',
 'TXN_7672686', 'TXN_9659401', 'TXN_5255387', 'TXN_7695629', 'TXN_6170729']
Length: 10000, dtype: str

In [24]:
cafe['Item'].unique()

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

In [25]:
cafe['Payment Method'].unique()

<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

In [26]:
cafe['Transaction ID']=cafe['Transaction ID'].str.strip('TXN')

In [27]:
cafe['Transaction ID'].unique()

<StringArray>
['_1961373', '_4977031', '_4271903', '_7034554', '_3160411', '_2602893',
 '_4433211', '_6699534', '_4717867', '_2064365',
 ...
 '_1538510', '_3897619', '_2739140', '_4766549', '_7851634', '_7672686',
 '_9659401', '_5255387', '_7695629', '_6170729']
Length: 10000, dtype: str

In [28]:
cafe['Transaction ID']=cafe['Transaction ID'].str.replace('_','CF')

In [29]:
cafe.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CF1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,CF4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,CF4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,CF7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,CF3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [30]:
cafe['Transaction ID'].isnull().sum()

np.int64(0)

In [32]:
cafe.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [33]:
cafe.dropna(inplace=True)

In [34]:
cafe.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [36]:
cafe.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CF1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,CF4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,CF4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,CF7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,CF3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
6,CF4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,CF6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
10,CF2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,CF3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,CF7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
15,CF2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
17,CF6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,CF8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
19,CF3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
20,CF3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
21,CF3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,CF5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
24,CF9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03
26,CF5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20
27,CF5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10
29,CF7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR
31,CF8927252,UNKNOWN,2,1.0,ERROR,Credit Card,ERROR,2023-11-06
34,CF8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
35,CF9130559,Sandwich,1,4.0,4.0,Credit Card,UNKNOWN,2023-05-28
37,CF1080432,Salad,2,5.0,10.0,Credit Card,In-store,2023-04-29
46,CF8078640,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-03
51,CF6342161,Salad,5,5.0,25.0,ERROR,Takeaway,2023-01-08
54,CF8614868,Smoothie,5,4.0,20.0,Digital Wallet,Takeaway,2023-12-05
55,CF5522862,Cookie,ERROR,1.0,2.0,Credit Card,Takeaway,2023-03-19
57,CF2080895,Cake,UNKNOWN,3.0,3.0,Digital Wallet,In-store,2023-04-19
58,CF6421134,Sandwich,4,4.0,16.0,Cash,Takeaway,2023-11-03
67,CF3068204,Cookie,1,1.0,1.0,Credit Card,Takeaway,2023-10-03
69,CF8471743,ERROR,5,3.0,15.0,Digital Wallet,In-store,2023-04-06
70,CF2621580,Tea,2,1.5,3.0,Cash,In-store,2023-03-22
71,CF4726376,Cake,2,3.0,6.0,Credit Card,In-store,2023-01-31
74,CF1900620,Smoothie,2,4.0,8.0,Credit Card,ERROR,2023-12-14
75,CF6420335,Coffee,1,2.0,2.0,Cash,Takeaway,2023-07-16
79,CF3829165,Juice,4,3.0,12.0,Cash,In-store,2023-06-15
80,CF3748616,Coffee,2,2.0,4.0,Credit Card,In-store,2023-12-09
83,CF5266394,Cake,3,3.0,9.0,Cash,In-store,2023-10-28
86,CF8718498,Cake,5,3.0,15.0,Credit Card,ERROR,2023-04-30
88,CF9487821,ERROR,1,5.0,5.0,Digital Wallet,Takeaway,2023-05-24
90,CF8976658,Tea,2,1.5,3.0,Credit Card,In-store,2023-08-16
94,CF6289610,Juice,3,3.0,UNKNOWN,Cash,Takeaway,2023-08-07
95,CF8268061,Salad,3,5.0,15.0,ERROR,Takeaway,2023-08-20
96,CF5220895,Salad,5,5.0,25.0,Cash,In-store,2023-06-10
97,CF3085509,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-04-15
98,CF9999113,Juice,4,3.0,12.0,Cash,Takeaway,2023-05-27
99,CF8779771,Coffee,4,2.0,8.0,Cash,In-store,2023-07-25
102,CF3808639,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-12-15

In [40]:
new=[0,2,1,3,4,5,6,7]

In [41]:
cafe=cafe[cafe.columns[new]]

In [42]:
cafe.head()

,Transaction ID,Quantity,Item,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CF1961373,2,Coffee,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,CF4977031,4,Cake,3.0,12.0,Cash,In-store,2023-05-16
2,CF4271903,4,Cookie,1.0,ERROR,Credit Card,In-store,2023-07-19
3,CF7034554,2,Salad,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,CF3160411,2,Coffee,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [43]:
cafe.set_index('Transaction ID',inplace=True)

In [46]:
cafe.head()

,Quantity,Item,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
Transaction ID,,,,,,,
CF1961373,2,Coffee,2.0,4.0,Credit Card,Takeaway,2023-09-08
CF4977031,4,Cake,3.0,12.0,Cash,In-store,2023-05-16
CF4271903,4,Cookie,1.0,ERROR,Credit Card,In-store,2023-07-19
CF7034554,2,Salad,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
CF3160411,2,Coffee,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [48]:
cafe.drop('Location',axis=1,inplace=True)

In [49]:
cafe.head()

,Quantity,Item,Price Per Unit,Total Spent,Payment Method,Transaction Date
Transaction ID,,,,,,
CF1961373,2,Coffee,2.0,4.0,Credit Card,2023-09-08
CF4977031,4,Cake,3.0,12.0,Cash,2023-05-16
CF4271903,4,Cookie,1.0,ERROR,Credit Card,2023-07-19
CF7034554,2,Salad,5.0,10.0,UNKNOWN,2023-04-27
CF3160411,2,Coffee,2.0,4.0,Digital Wallet,2023-06-11