In [1]:
import pandas as pd
import numpy as np

In [2]:
tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

In [3]:
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

In [4]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv' \
'')

In [5]:
amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

In [6]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [7]:
print('rows:',tips.shape[0])

rows: 244

In [8]:
print('columns:',tips.shape[1])

columns: 8

In [9]:
print(tips.head(5))
print(amazon.head(5))
print(hr.head(5))
print(wine_quality.head(5))
print(titanic.head(5))

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4
    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002
   employee_id  number_project  average_montly_hours  time_spend_company  \
0         1003               2                   157                   3
1         1005               5                   262                   6
2         1486               7                   272                   4
3         1038               5                   223                   5
4         1057               2                   159                   3

   Work_accident  left  promotion_last_5years department  salary
0              0     1                      0      sales     low
1              0     1                      0      sales  medium
2              0     1                      0      sales  medium
3              0     1                      0      sales     low
4              0     1                      0      sales     low
    type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7
1  white            6.3              0.30         0.34             1.6
2  white            8.1              0.28         0.40             6.9
3  white            7.2              0.23         0.32             8.5
4  white            7.2              0.23         0.32             8.5

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00
1      0.049                 14.0                 132.0   0.9940  3.30
2      0.050                 30.0                  97.0   0.9951  3.26
3      0.058                 47.0                 186.0   0.9956  3.19
4      0.058                 47.0                 186.0   0.9956  3.19

   sulphates  alcohol  quality
0       0.45      8.8        6
1       0.49      9.5        6
2       0.44     10.1        6
3       0.40      9.9        6
4       0.40      9.9        6
   pclass                                             name     sex      age  \
0       1                    Allen, Miss. Elisabeth Walton  female  29.0000
1       1                   Allison, Master. Hudson Trevor    male   0.9167
2       1                     Allison, Miss. Helen Loraine  female   2.0000
3       1             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

   sibsp  parch  ticket      fare    cabin embarked  survived
0      0      0   24160  211.3375       B5        S         1
1      1      2  113781  151.5500  C22 C26        S         1
2      1      2  113781  151.5500  C22 C26        S         0
3      1      2  113781  151.5500  C22 C26        S         0
4      1      2  113781  151.5500  C22 C26        S         0

In [10]:
tips.columns

Index(['Unnamed: 0', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time',
       'size'],
      dtype='str')

In [11]:
tips.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         244 non-null    float64
 3   sex         244 non-null    str
 4   smoker      244 non-null    str
 5   day         244 non-null    str
 6   time        244 non-null    str
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), str(4)
memory usage: 15.4 KB

In [12]:
hr.info()

<class 'pandas.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            14999 non-null  int64
 1   number_project         14999 non-null  int64
 2   average_montly_hours   14999 non-null  int64
 3   time_spend_company     14999 non-null  int64
 4   Work_accident          14999 non-null  int64
 5   left                   14999 non-null  int64
 6   promotion_last_5years  14999 non-null  int64
 7   department             14999 non-null  str
 8   salary                 14999 non-null  str
dtypes: int64(7), str(2)
memory usage: 1.0 MB

In [13]:
def summary(df):
    print(df.info())

summary(tips)

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         244 non-null    float64
 3   sex         244 non-null    str
 4   smoker      244 non-null    str
 5   day         244 non-null    str
 6   time        244 non-null    str
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), str(4)
memory usage: 15.4 KB
None

In [14]:
lst=[tips.shape[1], amazon.shape[1], hr.shape[1], wine_quality.shape[1], titanic.shape[1]]


x=np.array(lst)


np.max(x)

np.int64(13)

In [15]:
l=[1,2,3,4,5]
pd.Series(l,name='numbers',index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
Name: numbers, dtype: int64

In [16]:
d={'ENAME':['SMITH','ALLEN','WARD','JONES','MARTIN','BLAKE','CLARK','SCOTT','KING','TURNER'],
   'JOB':['CLERK','SALESMAN','SALESMAN','MANAGER','SALESMAN','MANAGER','MANAGER','ANALYST','PRESIDENT','SALESMAN'],
   'MGR':[7902,7698,7698,7839,7698,7839,7839,7566,7839,7698],
   'HIREDATE':['17-DEC-80','20-FEB-81','22-FEB-81','02-APR-81','28-SEP-81','01-MAY-81','09-JUN-81','19-APR-87','17-NOV-81','08-SEP-81'],
   'SAL':[800,1600,1250,2975,1250,2850,2450,3000,5000,1500],
   'COMM':[None,300,None,None,1400,None,None,None,None,-100],
   'DEPTNO':[20,30,30,20,30,30,10,20,10,30]}

In [17]:
df=pd.DataFrame(d)

In [18]:
df

    ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
0   SMITH      CLERK  7902  17-DEC-80   800     NaN      20
1   ALLEN   SALESMAN  7698  20-FEB-81  1600   300.0      30
2    WARD   SALESMAN  7698  22-FEB-81  1250     NaN      30
3   JONES    MANAGER  7839  02-APR-81  2975     NaN      20
4  MARTIN   SALESMAN  7698  28-SEP-81  1250  1400.0      30
5   BLAKE    MANAGER  7839  01-MAY-81  2850     NaN      30
6   CLARK    MANAGER  7839  09-JUN-81  2450     NaN      10
7   SCOTT    ANALYST  7566  19-APR-87  3000     NaN      20
8    KING  PRESIDENT  7839  17-NOV-81  5000     NaN      10
9  TURNER   SALESMAN  7698  08-SEP-81  1500  -100.0      30

In [19]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [20]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [21]:
titanic[['name','age','sex']]

                                                 name      age     sex
0                       Allen, Miss. Elisabeth Walton  29.0000  female
1                      Allison, Master. Hudson Trevor   0.9167    male
2                        Allison, Miss. Helen Loraine   2.0000  female
3                Allison, Mr. Hudson Joshua Creighton  30.0000    male
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000  female
...                                               ...      ...     ...
1304                             Zabour, Miss. Hileni  14.5000  female
1305                            Zabour, Miss. Thamine      NaN  female
1306                        Zakarian, Mr. Mapriededer  26.5000    male
1307                              Zakarian, Mr. Ortin  27.0000    male
1308                               Zimmerman, Mr. Leo  29.0000    male

[1309 rows x 3 columns]

In [22]:
titanic.loc[0:5,['name','age','sex']]

                                              name      age     sex
0                    Allen, Miss. Elisabeth Walton  29.0000  female
1                   Allison, Master. Hudson Trevor   0.9167    male
2                     Allison, Miss. Helen Loraine   2.0000  female
3             Allison, Mr. Hudson Joshua Creighton  30.0000    male
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000  female
5                              Anderson, Mr. Harry  48.0000    male

In [23]:
titanic.columns

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='str')

In [24]:
titanic.iloc[0:10,[-1,-2,-3,-4,-5]]

   survived embarked    cabin      fare    ticket
0         1        S       B5  211.3375     24160
1         1        S  C22 C26  151.5500    113781
2         0        S  C22 C26  151.5500    113781
3         0        S  C22 C26  151.5500    113781
4         0        S  C22 C26  151.5500    113781
5         1        S      E12   26.5500     19952
6         1        S       D7   77.9583     13502
7         0        S      A36    0.0000    112050
8         1        S     C101   51.4792     11769
9         0        C      NaN   49.5042  PC 17609

In [25]:
hr.columns

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='str')

In [26]:
hr[['employee_id','salary']]

       employee_id  salary
0             1003     low
1             1005  medium
2             1486  medium
3             1038     low
4             1057     low
...            ...     ...
14994        87670     low
14995        87673     low
14996        87679     low
14997        87681     low
14998        87684     low

[14999 rows x 2 columns]

In [27]:
titanic.loc[50:100,['name','sex']]

                                                  name     sex
50   Cardeza, Mrs. James Warburton Martinez (Charlo...  female
51                            Carlsson, Mr. Frans Olof    male
52                             Carrau, Mr. Francisco M    male
53                              Carrau, Mr. Jose Pedro    male
54                 Carter, Master. William Thornton II    male
55                           Carter, Miss. Lucile Polk  female
56                          Carter, Mr. William Ernest    male
57           Carter, Mrs. William Ernest (Lucile Polk)  female
58                              Case, Mr. Howard Brown    male
59   Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...  female
60                       Cavendish, Mr. Tyrell William    male
61   Cavendish, Mrs. Tyrell William (Julia Florence...  female
62                         Chaffee, Mr. Herbert Fuller    male
63   Chaffee, Mrs. Herbert Fuller (Carrie Constance...  female
64                       Chambers, Mr. Norman Campbell    male
65      Chambers, Mrs. Norman Campbell (Bertha Griggs)  female
66                         Chaudanson, Miss. Victorine  female
67                                Cherry, Miss. Gladys  female
68                            Chevre, Mr. Paul Romaine    male
69              Chibnall, Mrs. (Edith Martha Bowerman)  female
70               Chisholm, Mr. Roderick Robert Crispin    male
71                            Clark, Mr. Walter Miller    male
72       Clark, Mrs. Walter Miller (Virginia McDowell)  female
73                                Cleaver, Miss. Alice  female
74                         Clifford, Mr. George Quincy    male
75                          Colley, Mr. Edward Pomeroy    male
76                         Compton, Miss. Sara Rebecca  female
77                    Compton, Mr. Alexander Taylor Jr    male
78   Compton, Mrs. Alexander Taylor (Mary Eliza Ing...  female
79   Cornell, Mrs. Robert Clifford (Malvina Helen L...  female
80                           Crafton, Mr. John Bertram    male
81                        Crosby, Capt. Edward Gifford    male
82                             Crosby, Miss. Harriet R  female
83   Crosby, Mrs. Edward Gifford (Catherine Elizabe...  female
84                           Cumings, Mr. John Bradley    male
85   Cumings, Mrs. John Bradley (Florence Briggs Th...  female
86                              Daly, Mr. Peter Denis     male
87                         Daniel, Mr. Robert Williams    male
88                                Daniels, Miss. Sarah  female
89                              Davidson, Mr. Thornton    male
90                Davidson, Mrs. Thornton (Orian Hays)  female
91                             Dick, Mr. Albert Adrian    male
92           Dick, Mrs. Albert Adrian (Vera Gillespie)  female
93                               Dodge, Dr. Washington    male
94                           Dodge, Master. Washington    male
95               Dodge, Mrs. Washington (Ruth Vidaver)  female
96                          Douglas, Mr. Walter Donald    male
97   Douglas, Mrs. Frederick Charles (Mary Helene B...  female
98         Douglas, Mrs. Walter Donald (Mahala Dutton)  female
99   Duff Gordon, Lady. (Lucille Christiana Sutherl...  female
100       Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")    male

In [28]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [29]:
wine_quality.select_dtypes(include='number').head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [30]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [31]:
titanic[titanic['age']>50]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,1
33,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1068,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S,0
1225,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S,0
1235,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,0
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1287,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S,0

In [32]:
titanic[titanic['sex']=='female']
titanic[(titanic['age']>20) & (titanic['age']<40)]
tips[tips['total_bill']>30]

     Unnamed: 0  total_bill    tip     sex smoker   day    time  size
11           11       35.26   5.00  Female     No   Sun  Dinner     4
23           23       39.42   7.58    Male     No   Sat  Dinner     4
39           39       31.27   5.00    Male     No   Sat  Dinner     3
44           44       30.40   5.60    Male     No   Sun  Dinner     4
47           47       32.40   6.00    Male     No   Sun  Dinner     4
52           52       34.81   5.20  Female     No   Sun  Dinner     4
56           56       38.01   3.00    Male    Yes   Sat  Dinner     4
59           59       48.27   6.73    Male     No   Sat  Dinner     4
83           83       32.68   5.00    Male    Yes  Thur   Lunch     2
85           85       34.83   5.17  Female     No  Thur   Lunch     4
95           95       40.17   4.73    Male    Yes   Fri  Dinner     4
102         102       44.30   2.50  Female    Yes   Sat  Dinner     3
112         112       38.07   4.00    Male     No   Sun  Dinner     3
141         141       34.30   6.70    Male     No  Thur   Lunch     6
142         142       41.19   5.00    Male     No  Thur   Lunch     5
156         156       48.17   5.00    Male     No   Sun  Dinner     6
167         167       31.71   4.50    Male     No   Sun  Dinner     4
170         170       50.81  10.00    Male    Yes   Sat  Dinner     3
173         173       31.85   3.18    Male    Yes   Sun  Dinner     2
175         175       32.90   3.11    Male    Yes   Sun  Dinner     2
179         179       34.63   3.55    Male    Yes   Sun  Dinner     2
180         180       34.65   3.68    Male    Yes   Sun  Dinner     4
182         182       45.35   3.50    Male    Yes   Sun  Dinner     3
184         184       40.55   3.00    Male    Yes   Sun  Dinner     2
187         187       30.46   2.00    Male    Yes   Sun  Dinner     5
197         197       43.11   5.00  Female    Yes  Thur   Lunch     4
207         207       38.73   3.00    Male    Yes   Sat  Dinner     4
210         210       30.06   2.00    Male    Yes   Sat  Dinner     3
212         212       48.33   9.00    Male     No   Sat  Dinner     4
219         219       30.14   3.09  Female    Yes   Sat  Dinner     4
237         237       32.83   1.17    Male    Yes   Sat  Dinner     2
238         238       35.83   4.67  Female     No   Sat  Dinner     3

In [33]:
titanic.head(2)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1

In [34]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [35]:
titanic[(titanic['sex']=='female') & (titanic['age']>20) & (titanic['age']<40) & (titanic['pclass']==1) & (titanic['survived']==1)]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
18,1,"Bazzani, Miss. Albina",female,32.0,0,0,11813,76.2917,D15,C,1
24,1,"Bird, Miss. Ellen",female,29.0,0,0,PC 17483,221.7792,C97,S,1
...,...,...,...,...,...,...,...,...,...,...,...
302,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,1
309,1,"Wick, Miss. Mary Natalie",female,31.0,0,2,36928,164.8667,C7,S,1
315,1,"Willard, Miss. Constance",female,21.0,0,0,113795,26.5500,NaN,S,1
319,1,"Wilson, Miss. Helen Alice",female,31.0,0,0,16966,134.5000,E39 E41,C,1
322,1,"Young, Miss. Marie Grice",female,36.0,0,0,PC 17760,135.6333,C32,C,1

In [36]:
hr.info()

<class 'pandas.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            14999 non-null  int64
 1   number_project         14999 non-null  int64
 2   average_montly_hours   14999 non-null  int64
 3   time_spend_company     14999 non-null  int64
 4   Work_accident          14999 non-null  int64
 5   left                   14999 non-null  int64
 6   promotion_last_5years  14999 non-null  int64
 7   department             14999 non-null  str
 8   salary                 14999 non-null  str
dtypes: int64(7), str(2)
memory usage: 1.0 MB

In [37]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [38]:
hr[(hr['salary']=='high') | (hr['salary']=='medium')]

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
60,1393,5,226,5,0,1,0,management,medium
61,1399,7,308,4,0,1,0,IT,medium
62,1404,6,244,5,0,1,0,IT,medium
...,...,...,...,...,...,...,...,...,...
14980,20751,5,238,5,0,1,0,technical,high
14982,87608,2,137,3,0,1,0,technical,medium
14983,87610,5,257,5,0,1,0,technical,medium
14984,87612,2,148,3,0,1,0,technical,medium
14985,87624,5,254,5,0,1,0,technical,medium

In [39]:
titanic.sort_values(by='age', ascending=False)
titanic.sort_index(ascending=False)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1

In [40]:
tips.nlargest(10,'tip')

     Unnamed: 0  total_bill    tip     sex smoker   day    time  size
170         170       50.81  10.00    Male    Yes   Sat  Dinner     3
212         212       48.33   9.00    Male     No   Sat  Dinner     4
23           23       39.42   7.58    Male     No   Sat  Dinner     4
59           59       48.27   6.73    Male     No   Sat  Dinner     4
141         141       34.30   6.70    Male     No  Thur   Lunch     6
183         183       23.17   6.50    Male    Yes   Sun  Dinner     4
214         214       28.17   6.50  Female    Yes   Sat  Dinner     3
47           47       32.40   6.00    Male     No   Sun  Dinner     4
239         239       29.03   5.92    Male     No   Sat  Dinner     3
88           88       24.71   5.85    Male     No  Thur   Lunch     2

In [41]:
titanic['age'].isna().head(5)
titanic['age']=titanic['age'].fillna(titanic['age'].mean(), inplace=True)

C:\Users\ashut\AppData\Local\Temp\ipykernel_13860\2947862551.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  titanic['age']=titanic['age'].fillna(titanic['age'].mean(), inplace=True)

In [42]:
titanic.isna().sum()

pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

titanic.isnull().sum()

In [43]:
titanic.isna().mean()*100

pclass       0.000000
name         0.000000
sex          0.000000
age          0.000000
sibsp        0.000000
parch        0.000000
ticket       0.000000
fare         0.076394
cabin       77.463713
embarked     0.152788
survived     0.000000
dtype: float64

In [44]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [45]:
amazon.duplicated().sum()

np.int64(30)

In [46]:
amazon.drop_duplicates(inplace=True)

In [47]:
amazon.duplicated().sum()

np.int64(0)

In [48]:
wine_quality['type'].unique()

<StringArray>
['white', 'red']
Length: 2, dtype: str

In [49]:
d={'red': 'red wine', 'white': 'white wine'}

In [50]:
wine_quality['type']=wine_quality['type'].map(d)

In [51]:
wine_quality['type'][0]='new wine'

C:\Users\ashut\AppData\Local\Temp\ipykernel_13860\590136369.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  wine_quality['type'][0]='new wine'

In [52]:
import pandas as pd

In [53]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv'
'')

In [54]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [55]:
titanic['name'][0]

'Allen, Miss. Elisabeth Walton'

In [56]:
# out=[]
# for i in titanic['name']:
#     output=i.split(',')[1].split('.')[0]
#     out.append(output)
# out

In [57]:
# titanic['name']=out

In [58]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [59]:
titanic.isna().sum()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [60]:
import numpy as np

In [61]:
titanic['age'].isnull().sum()

np.int64(263)

In [62]:
med=titanic['age'].median()

In [63]:
titanic['age']=titanic['age'].fillna(med)

In [64]:
titanic['age'].unique()

array([29.    ,  0.9167,  2.    , 30.    , 25.    , 48.    , 63.    ,
       39.    , 53.    , 71.    , 47.    , 18.    , 24.    , 26.    ,
       80.    , 28.    , 50.    , 32.    , 36.    , 37.    , 42.    ,
       19.    , 35.    , 45.    , 40.    , 58.    , 22.    , 41.    ,
       44.    , 59.    , 60.    , 33.    , 17.    , 11.    , 14.    ,
       49.    , 76.    , 46.    , 27.    , 64.    , 55.    , 70.    ,
       38.    , 51.    , 31.    ,  4.    , 54.    , 23.    , 43.    ,
       52.    , 16.    , 32.5   , 21.    , 15.    , 65.    , 28.5   ,
       45.5   , 56.    , 13.    , 61.    , 34.    ,  6.    , 57.    ,
       62.    , 67.    ,  1.    , 12.    , 20.    ,  0.8333,  8.    ,
        0.6667,  7.    ,  3.    , 36.5   , 18.5   ,  5.    , 66.    ,
        9.    ,  0.75  , 70.5   , 22.5   ,  0.3333,  0.1667, 40.5   ,
       10.    , 23.5   , 34.5   , 20.5   , 30.5   , 55.5   , 38.5   ,
       14.5   , 24.5   , 60.5   , 74.    ,  0.4167, 11.5   , 26.5   ])

In [65]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [66]:


total=titanic.isnull().sum().sum()
titanic.isnull().sum()*100/len(titanic)

pclass       0.000000
name         0.000000
sex          0.000000
age          0.000000
sibsp        0.000000
parch        0.000000
ticket       0.000000
fare         0.076394
cabin       77.463713
embarked     0.152788
survived     0.000000
dtype: float64

In [67]:
len(titanic)

1309

In [68]:
titanic.loc[0:5,'name']

0                      Allen, Miss. Elisabeth Walton
1                     Allison, Master. Hudson Trevor
2                       Allison, Miss. Helen Loraine
3               Allison, Mr. Hudson Joshua Creighton
4    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
5                                Anderson, Mr. Harry
Name: name, dtype: str

In [69]:
lst=[]
for i in titanic['name']:
    output=i.split(',')[1].split('.')[0]
    lst.append(output)
titanic['name']=lst

In [70]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,Miss,female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,Master,male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,Miss,female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,Mr,male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,Mrs,female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [71]:
titanic['title']=lst

In [72]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,title
0,1,Miss,female,29.0000,0,0,24160,211.3375,B5,S,1,Miss
1,1,Master,male,0.9167,1,2,113781,151.5500,C22 C26,S,1,Master
2,1,Miss,female,2.0000,1,2,113781,151.5500,C22 C26,S,0,Miss
3,1,Mr,male,30.0000,1,2,113781,151.5500,C22 C26,S,0,Mr
4,1,Mrs,female,25.0000,1,2,113781,151.5500,C22 C26,S,0,Mrs

In [73]:
d=[10,0,1,2,3,4,5,6,7,8,9]
titanic=titanic[titanic.columns[d]]

In [74]:
titanic.isna().sum()*100/len(titanic)

titanic.drop('cabin',inplace=True,axis=1)

In [75]:
titanic.head()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,1,Miss,female,29.0000,0,0,24160,211.3375,S
1,1,1,Master,male,0.9167,1,2,113781,151.5500,S
2,0,1,Miss,female,2.0000,1,2,113781,151.5500,S
3,0,1,Mr,male,30.0000,1,2,113781,151.5500,S
4,0,1,Mrs,female,25.0000,1,2,113781,151.5500,S

In [76]:
titanic.duplicated().sum()

np.int64(22)

In [77]:
titanic.head()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,1,Miss,female,29.0000,0,0,24160,211.3375,S
1,1,1,Master,male,0.9167,1,2,113781,151.5500,S
2,0,1,Miss,female,2.0000,1,2,113781,151.5500,S
3,0,1,Mr,male,30.0000,1,2,113781,151.5500,S
4,0,1,Mrs,female,25.0000,1,2,113781,151.5500,S

In [78]:
d={'title':'Title','pclass':'pass_class','name':'Name','sex':'Sex'}
titanic=titanic.rename(columns=d)

In [79]:
titanic.head()

,survived,pass_class,Name,Sex,age,sibsp,parch,ticket,fare,embarked
0,1,1,Miss,female,29.0000,0,0,24160,211.3375,S
1,1,1,Master,male,0.9167,1,2,113781,151.5500,S
2,0,1,Miss,female,2.0000,1,2,113781,151.5500,S
3,0,1,Mr,male,30.0000,1,2,113781,151.5500,S
4,0,1,Mrs,female,25.0000,1,2,113781,151.5500,S

In [80]:
hr.duplicated().sum()

np.int64(0)

In [81]:
hr.info()

<class 'pandas.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            14999 non-null  int64
 1   number_project         14999 non-null  int64
 2   average_montly_hours   14999 non-null  int64
 3   time_spend_company     14999 non-null  int64
 4   Work_accident          14999 non-null  int64
 5   left                   14999 non-null  int64
 6   promotion_last_5years  14999 non-null  int64
 7   department             14999 non-null  str
 8   salary                 14999 non-null  str
dtypes: int64(7), str(2)
memory usage: 1.0 MB

In [82]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [1]:
import pandas as pd

In [8]:
appliances=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/uncleaned_appliances.csv')

In [9]:
appliances.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN

In [10]:
appliances=appliances.drop(['goods-title-link--jump href','goods-title-link--jump','goods-title-link'],axis=1)

In [11]:
appliances.head()

,rank-title,rank-sub,price,discount,selling_proposition
0,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN
1,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN
2,NaN,NaN,$1.80,NaN,400+ sold recently
3,NaN,NaN,$0.88,-72%,5.6k+ sold recently
4,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN

In [20]:
appliances['price']=appliances['price'].str.strip('$')

appliances['price']=appliances['price'].str.replace(',','')

appliances['price'].unique()

appliances['price']=appliances['price'].astype(float)

In [23]:
price=[]
for i in appliances['price']:
    output= 'Rs'+str(i*95)
    price.append(output)

appliances['price_in_inr']=price

In [24]:
appliances.head()

,rank-title,rank-sub,price,discount,selling_proposition,price_in_inr
0,#1 Best Sellers,in Give Gifts,2.03,-22%,NaN,Rs192.85
1,#4 Best Sellers,in Top rated in Portable Fans,6.48,-20%,NaN,Rs615.6
2,NaN,NaN,1.80,NaN,400+ sold recently,Rs171.0
3,NaN,NaN,0.88,-72%,5.6k+ sold recently,Rs83.6
4,#6 Best Sellers,in Oral Irrigators,12.06,-40%,NaN,Rs1145.7

In [37]:
appliances['selling_proposition']=appliances['selling_proposition'].fillna('0 Sold recently')

In [38]:
appliances['selling_proposition'].unique()

<StringArray>
[    '0 Sold recently',  '400+ sold recently', '5.6k+ sold recently',
   '50+ sold recently',   '30+ sold recently',   '60+ sold recently',
  '100+ sold recently',  '200+ sold recently', '8.7k+ sold recently',
   '10+ sold recently', '1.6k+ sold recently',   '20+ sold recently',
  '10k+ sold recently',   '80+ sold recently',  '300+ sold recently',
  '900+ sold recently',  '600+ sold recently',   '70+ sold recently',
   '40+ sold recently', '1.8k+ sold recently', '5.0k+ sold recently',
 '1.1k+ sold recently', '2.0k+ sold recently',  '500+ sold recently',
   '90+ sold recently',  '800+ sold recently', '2.2k+ sold recently',
 '1.5k+ sold recently', '1.2k+ sold recently', '1.3k+ sold recently',
 '3.4k+ sold recently',  '700+ sold recently', '2.4k+ sold recently',
 '6.3k+ sold recently', '2.6k+ sold recently', '3.8k+ sold recently',
 '2.1k+ sold recently', '1.0k+ sold recently', '4.7k+ sold recently',
 '2.9k+ sold recently', '1.9k+ sold recently', '5.4k+ sold recently',
 '3.2k+ sold recently', '7.8k+ sold recently', '1.4k+ sold recently',
 '7.0k+ sold recently', '5.1k+ sold recently', '6.9k+ sold recently',
 '1.7k+ sold recently', '2.3k+ sold recently', '7.7k+ sold recently',
 '4.5k+ sold recently', '2.5k+ sold recently', '2.7k+ sold recently',
 '5.2k+ sold recently', '4.3k+ sold recently', '4.8k+ sold recently',
 '4.2k+ sold recently', '4.4k+ sold recently', '3.1k+ sold recently',
 '2.8k+ sold recently', '5.8k+ sold recently', '4.0k+ sold recently',
 '3.7k+ sold recently', '3.5k+ sold recently']
Length: 65, dtype: str

In [39]:
appliances['selling_proposition'].head()

0        0 Sold recently
1        0 Sold recently
2     400+ sold recently
3    5.6k+ sold recently
4        0 Sold recently
Name: selling_proposition, dtype: str

In [154]:
appliances.head()

    price
0   $2.03
1   $6.48
2   $1.80
3   $0.88
4  $12.06

In [4]:
appliances=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/uncleaned_appliances.csv')

URLError: <urlopen error [Errno 11001] getaddrinfo failed>