In [7]:
import pandas as pd
import numpy as np

In [28]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv'
'')
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [26]:
# Dropping unwanted rows.

# # Syntax:
#  var.drop(row_index)-> for single row
# var.drop([row_index1, row_index2,....])-> for multiple rows

In [8]:
d={'ENAME':['SMITH','ALLEN','WARD','JONES','MARTIN','BLAKE','CLARK','SCOTT','KING',np.nan,'TURNER'],
   'Eid':  [7369,7499,7521,7566,7698,7782,7788,7902,7934,7844,np.nan],
   'Salary':['8LPA','10LPA','9LPA','12LPA','15LPA','14LPA','13LPA','16LPA','20LPA','11LPA',np.nan]}

In [29]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
df=pd.DataFrame(d)

In [10]:
df

     ENAME     Eid Salary
0    SMITH  7369.0   8LPA
1    ALLEN  7499.0  10LPA
2     WARD  7521.0   9LPA
3    JONES  7566.0  12LPA
4   MARTIN  7698.0  15LPA
5    BLAKE  7782.0  14LPA
6    CLARK  7788.0  13LPA
7    SCOTT  7902.0  16LPA
8     KING  7934.0  20LPA
9      NaN  7844.0  11LPA
10  TURNER     NaN    NaN

In [11]:
df.drop(10)

    ENAME     Eid Salary
0   SMITH  7369.0   8LPA
1   ALLEN  7499.0  10LPA
2    WARD  7521.0   9LPA
3   JONES  7566.0  12LPA
4  MARTIN  7698.0  15LPA
5   BLAKE  7782.0  14LPA
6   CLARK  7788.0  13LPA
7   SCOTT  7902.0  16LPA
8    KING  7934.0  20LPA
9     NaN  7844.0  11LPA

In [12]:
df.drop([5,9])

     ENAME     Eid Salary
0    SMITH  7369.0   8LPA
1    ALLEN  7499.0  10LPA
2     WARD  7521.0   9LPA
3    JONES  7566.0  12LPA
4   MARTIN  7698.0  15LPA
6    CLARK  7788.0  13LPA
7    SCOTT  7902.0  16LPA
8     KING  7934.0  20LPA
10  TURNER     NaN    NaN

In [13]:
# axis=1---> column
# axis=0----> row

In [33]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [25]:
tips.head()

      total_bill   tip smoker  day    time
size
2          16.99  1.01     No  Sun  Dinner
3          10.34  1.66     No  Sun  Dinner
3          21.01  3.50     No  Sun  Dinner
2          23.68  3.31     No  Sun  Dinner
4          24.59  3.61     No  Sun  Dinner

In [20]:
# set_index()-> It will set the specified columns as index of dataframe.

# Syntax: 
# var.set_index('col_name',inplace=true)

In [ ]:
# tips.set_index('size',inplace=True)

In [35]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [38]:
amazon.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [39]:
amazon.set_index('ano',inplace=True)

In [40]:
amazon.head()

          mes estado   numero  encontro
ano
1998  Janeiro   Acre  0 Fires  1/1/1998
1999  Janeiro   Acre  0 Fires  1/1/1999
2000  Janeiro   Acre  0 Fires  1/1/2000
2001  Janeiro   Acre  0 Fires  1/1/2001
2002  Janeiro   Acre  0 Fires  1/1/2002

In [41]:
amazon.reset_index(inplace=True)

In [42]:
amazon.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [43]:
appliances=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/uncleaned_appliances.csv')

In [44]:
appliances.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN

In [46]:
appliances.duplicated().sum()

np.int64(209)

In [51]:
appliances.drop_duplicates(inplace=True)

In [53]:
appliances.duplicated().sum()

np.int64(0)

In [55]:
appliances.shape

(3777, 8)

In [57]:
appliances.notnull().sum()

goods-title-link--jump           40
goods-title-link--jump href      40
rank-title                      559
rank-sub                        559
price                          3777
discount                       2259
selling_proposition            1352
goods-title-link               3737
dtype: int64

In [60]:
appliances['goods-title-link'].unique()

<StringArray>
[                                                                                                                                                                                                                                                   nan,
                                                                                            '4pcs Makeup Sponge Beauty Egg Set - Makeup Sponge For Foundation Blending With Egg Holder, Perfectly Used For Cream, Powder, Blush, Concealer, And Liquid',
                                                                                                                 '1pc Salon Tools Black Pink Universal Silicone Hair Dryer Diffuser Hood Adjustable Temperature Dispersion Resistant Drying Hair Dryer',
                                                                                                                                                                                    'Portable Lithium Battery Powered Hair Trimmer & Nose Hair Trimmer',
                                                                                                                        'Multifunctional Manual Food Chopper, Kitchen Vegetable Fruit Onion Garlic Nuts Herb Slicer, Hand-Powered Mixing Cutter, Green',
                                                                                                     '1 Set Of 2 Portable Fan Cleaning Brushes, Household Multi-Purpose Keyboard And Gap Cleaning Small Brush - Deep Into The Gap, Easily Remove Dust.',
 'Smart Electric Toothbrush With 6 Modes 42000vpm & Smart Timer - Effectively Cleans Teeth & Gums, Rechargeable USB Electric Toothbrush With 4/8 Replacement Head, Electric Toothbrush For Adults, Available In 3 Colors, Great Gift Father's Day Gift',
                                                                                                                                                                     '1pc 12.7cm Aluminum Metal Electric Battery Type Eyebrow Shaver Nose Hair Trimmer',
                                                                   'Professional Curler, Electrically Heated Automatic Curler, Negative Ion Electric Clip Curler, Portable Heated Hair Styling Tool For Home Use, Salon, Hair Salon, Mother's Day Gift',
                                                                                                                                     '1pc Mini Bag Sealer, Rechargeable Portable Sealing Machine, Handheld Plastic Vacuum Sealer For Kitchen Packaging',
 ...
                                                                                                                  'WhizMax 14000 BTU Dual Hose Portable Air Conditioner And Heater - Dehumidifier, Fan - For Rooms Up To 700 Sq. Ft - AC Unit + Heater',
                                                                                                              'Healthy Ceramic Nonstick, 12" 5QT Square Electric Skillet With Glass Lid, Dishwasher Safe, Adjustable Temperature Control, PFAS-, Black',
                                                                                  'BOSSCARE 3D Full Body SL Track Massage Chair, APP Control, Body Scanning, Zero Gravity Shiatsu Massaging Recliner, Heating Therapy, Space-Saving, Bluetooth Speaker',
                                                                                                                                                                             'Unbeatablesale 12 X 24 X 1 In. Fiberglass 4 MERV Air Filter - Pack Of 12',
                                                                                             'Artist Hand Full Body Massage Chair - SL Track Zero Gravity Recliner With 12 Modes, Bluetooth, Body Scan, Foot Roller, Airbags Massage, AI Voice Control',
                                                                                                                                                                                                             'Unbeatablesale 142Mhz .25 Wave Kulduckie',
                                                                                                                                                                                                   'Unbeatablesale 440-460Mhz Load And Tip Only -Black',
                                                                                                                                              'TaoTronics Air Fryer, 1700W 14.8 QT, 9 In 1 Air Fryer Oven, Oil-Less Cooker With Rotisserie Shaft AF010',
                                                                                                                                         'Air Fryer 5.3 Quart, Digital Oilless Frying Cooker, Auto Shut Off, Stainless Steel, 8 Preset Programs, 1700W',
                                                             'Up To 350lbs Okin Motor Power Lift Recliner Chair For Elderly, Heavy Duty Motion Mechanism With 8-Point Vibration Massage And Lumbar Heating, Two Cup Holders And USB Charge Port, Brown']
Length: 3591, dtype: str

In [62]:
appliances.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN

In [69]:
appliances.drop(['goods-title-link--jump','goods-title-link--jump href','goods-title-link'],inplace=True, axis= 1)

In [70]:
appliances.head()

,rank-title,rank-sub,price,discount,selling_proposition
0,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN
3,NaN,NaN,$0.88,-72%,5.6k+ sold recently
4,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN
5,#10 Best Sellers,in Refrigerators & Freezers,$2.70,NaN,NaN
6,#8 Best Sellers,in Other Household Appliances,$3.50,NaN,NaN

In [71]:
appliances['rank-title'].unique()

<StringArray>
[ '#1 Best Sellers',                nan,  '#6 Best Sellers',
 '#10 Best Sellers',  '#8 Best Sellers',  '#9 Best Sellers',
  '#5 Best Sellers',  '#2 Best Sellers',  '#7 Best Sellers',
  '#3 Best Sellers',  '#4 Best Sellers']
Length: 11, dtype: str

In [77]:
appliances['rank-title']=appliances['rank-title'].str.strip('# Best Sellers')

In [78]:
appliances.head()

,rank-title,rank-sub,price,discount,selling_proposition
0,1,in Give Gifts,$2.03,-22%,NaN
3,NaN,NaN,$0.88,-72%,5.6k+ sold recently
4,6,in Oral Irrigators,$12.06,-40%,NaN
5,10,in Refrigerators & Freezers,$2.70,NaN,NaN
6,8,in Other Household Appliances,$3.50,NaN,NaN

NameError: name 'Int64' is not defined

In [81]:
appliances['rank-title']=appliances['rank-title'].astype('Int64')

In [82]:
appliances.head()

,rank-title,rank-sub,price,discount,selling_proposition
0,1,in Give Gifts,$2.03,-22%,NaN
3,<NA>,NaN,$0.88,-72%,5.6k+ sold recently
4,6,in Oral Irrigators,$12.06,-40%,NaN
5,10,in Refrigerators & Freezers,$2.70,NaN,NaN
6,8,in Other Household Appliances,$3.50,NaN,NaN

In [83]:
appliances['rank-title'].unique()

<IntegerArray>
[1, <NA>, 6, 10, 8, 9, 5, 2, 7, 3, 4]
Length: 11, dtype: Int64

In [86]:
avg= round(appliances['rank-title'].mean())

avg

5

In [ ]:
ua['rank-title']