In [2]:
import pandas as pd
import numpy as np

In [3]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv' \
'')
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

amazon.head()

In [4]:
amazon['mes'].unique()

<StringArray>
[  'Janeiro', 'Fevereiro',     'Março',     'Abril',      'Maio',     'Junho',
     'Julho',    'Agosto',  'Setembro',   'Outubro',  'Novembro',  'Dezembro']
Length: 12, dtype: str

In [5]:
amazon['numero'].unique()

<StringArray>
[ '0 Fires', '10 Fires', '12 Fires',  '4 Fires',  '1 Fires',  '3 Fires',
  '5 Fires',  '2 Fires', '11 Fires',        nan,
 ...
    '2.913',      '718',    '2.272',    '1.591',     '3.68',    '2.155',
    '4.844',    '2.032',      '833',      '623']
Length: 1729, dtype: str

In [6]:
amazon['numero']=amazon['numero'].str.strip('Fires')

In [7]:
amazon['numero'].unique()

<StringArray>
[   '0 ',   '10 ',   '12 ',    '4 ',    '1 ',    '3 ',    '5 ',    '2 ',
   '11 ',     nan,
 ...
 '2.913',   '718', '2.272', '1.591',  '3.68', '2.155', '4.844', '2.032',
   '833',   '623']
Length: 1729, dtype: str

In [8]:
    # Handling missing value("nan" values)

# 1)  Deleting all nan values.

# syntax:
#     var.dropna(inplace=true)

In [9]:
amazon['numero'].isnull().sum()

np.int64(132)

In [10]:
amazon['numero'].dropna(inplace=True)

In [11]:
amazon['numero'].isnull().sum()

np.int64(132)

In [12]:
d={'ENAME':['SMITH','ALLEN','WARD','JONES','MARTIN','BLAKE','CLARK','SCOTT','KING',np.nan,'TURNER'],
   'Eid':  [7369,7499,7521,7566,7698,7782,7788,7902,7934,7844,np.nan],
   'Salary':['8LPA','10LPA','9LPA','12LPA','15LPA','14LPA','13LPA','16LPA','20LPA','11LPA',np.nan]}

In [13]:
df=pd.DataFrame(d)

In [14]:
df

     ENAME     Eid Salary
0    SMITH  7369.0   8LPA
1    ALLEN  7499.0  10LPA
2     WARD  7521.0   9LPA
3    JONES  7566.0  12LPA
4   MARTIN  7698.0  15LPA
5    BLAKE  7782.0  14LPA
6    CLARK  7788.0  13LPA
7    SCOTT  7902.0  16LPA
8     KING  7934.0  20LPA
9      NaN  7844.0  11LPA
10  TURNER     NaN    NaN

In [15]:
df.dropna(inplace=True)

In [16]:
df

    ENAME     Eid Salary
0   SMITH  7369.0   8LPA
1   ALLEN  7499.0  10LPA
2    WARD  7521.0   9LPA
3   JONES  7566.0  12LPA
4  MARTIN  7698.0  15LPA
5   BLAKE  7782.0  14LPA
6   CLARK  7788.0  13LPA
7   SCOTT  7902.0  16LPA
8    KING  7934.0  20LPA

In [17]:
wine_quality['fixed acidity'].isnull().sum()

np.int64(10)

In [18]:
wine_quality=wine_quality.dropna()

In [19]:
wine_quality['fixed acidity'].isnull().sum()

np.int64(0)

In [20]:
wine_quality.shape

(6463, 13)

In [21]:
amazon.shape

(6454, 5)

In [22]:
amazon.isna().sum()

ano           0
mes           0
estado        0
numero      132
encontro      0
dtype: int64

In [23]:
amazon.dropna(inplace=True)

In [24]:
amazon.shape

(6322, 5)

In [25]:
# Filling Nan values:
# 1) fillna()
# 2) ffill()
# 3) bbill()

# 1) fillna():- It will fill the nan values with the given value.

# Syntax:
#        var['col_name']=var['col_name'].fillna(value, inplace=True)

In [26]:
e={'STUDENT_ID':[1,2,3,4,5, np.nan],
   'STUDENT_NAME':['SMITH','ALLEN','WARD','JONES','MARTIN',np.nan],
   'STUDENT_COURSE':['B.TECH','BSC','BA','LLB','M.TECH',np.nan]}

In [27]:
df=pd.DataFrame(e)

In [28]:
df

   STUDENT_ID STUDENT_NAME STUDENT_COURSE
0         1.0        SMITH         B.TECH
1         2.0        ALLEN            BSC
2         3.0         WARD             BA
3         4.0        JONES            LLB
4         5.0       MARTIN         M.TECH
5         NaN          NaN            NaN

In [29]:
df['STUDENT_COURSE']=df['STUDENT_COURSE'].fillna('unknown')

In [30]:
df

   STUDENT_ID STUDENT_NAME STUDENT_COURSE
0         1.0        SMITH         B.TECH
1         2.0        ALLEN            BSC
2         3.0         WARD             BA
3         4.0        JONES            LLB
4         5.0       MARTIN         M.TECH
5         NaN          NaN        unknown

In [31]:
df['STUDENT_NAME']=df['STUDENT_NAME'].fillna('unknown')

In [32]:
df

   STUDENT_ID STUDENT_NAME STUDENT_COURSE
0         1.0        SMITH         B.TECH
1         2.0        ALLEN            BSC
2         3.0         WARD             BA
3         4.0        JONES            LLB
4         5.0       MARTIN         M.TECH
5         NaN      unknown        unknown

In [33]:
avg= df['STUDENT_ID'].mean()

In [34]:
avg

np.float64(3.0)

In [35]:
df['STUDENT_ID']=df['STUDENT_ID'].fillna(avg)

In [36]:
df

   STUDENT_ID STUDENT_NAME STUDENT_COURSE
0         1.0        SMITH         B.TECH
1         2.0        ALLEN            BSC
2         3.0         WARD             BA
3         4.0        JONES            LLB
4         5.0       MARTIN         M.TECH
5         3.0      unknown        unknown

In [37]:
# 2) ffill(): It will fill the value with its previous value 

# Syntax: var['col_name']=var['col_name'].ffill()

In [38]:
# 3) bfill()-> It will fill the value of its next value

# syntax: var['col_name']=var['col_name'].bfill()

In [39]:
# Rearranging the order of columns.

# Syntax: 
# new_order=[col_index1,col_index2....]
# var=var[var.columns[new_order]]

In [40]:
df

   STUDENT_ID STUDENT_NAME STUDENT_COURSE
0         1.0        SMITH         B.TECH
1         2.0        ALLEN            BSC
2         3.0         WARD             BA
3         4.0        JONES            LLB
4         5.0       MARTIN         M.TECH
5         3.0      unknown        unknown

In [41]:
new=[2,1,0]

In [42]:
df=df[df.columns[new]]

In [43]:
df

  STUDENT_COURSE STUDENT_NAME  STUDENT_ID
0         B.TECH        SMITH         1.0
1            BSC        ALLEN         2.0
2             BA         WARD         3.0
3            LLB        JONES         4.0
4         M.TECH       MARTIN         5.0
5        unknown      unknown         3.0

In [44]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [45]:
new=[7,6,5,4,3,2,1,0]

In [46]:
tips=tips[tips.columns[new]]

In [47]:
tips.head()

   size    time  day smoker     sex   tip  total_bill  Unnamed: 0
0     2  Dinner  Sun     No  Female  1.01       16.99           0
1     3  Dinner  Sun     No    Male  1.66       10.34           1
2     3  Dinner  Sun     No    Male  3.50       21.01           2
3     2  Dinner  Sun     No    Male  3.31       23.68           3
4     4  Dinner  Sun     No  Female  3.61       24.59           4

In [48]:
# resetting the index: 
# it will reset the index of dataframe and old index will become the column.
# Syntax:
# var.reset_index(inplace=True)

In [49]:
# # Dropping unwanted columns.

 # Syntax:
# var.drop('col_name',axis=1)
# var.drop(['col_name','col_name2'...],axis=1) for multiple columns

In [50]:
df.head()

  STUDENT_COURSE STUDENT_NAME  STUDENT_ID
0         B.TECH        SMITH         1.0
1            BSC        ALLEN         2.0
2             BA         WARD         3.0
3            LLB        JONES         4.0
4         M.TECH       MARTIN         5.0

In [51]:
df=df.drop('STUDENT_COURSE',axis=1)

In [52]:
df

  STUDENT_NAME  STUDENT_ID
0        SMITH         1.0
1        ALLEN         2.0
2         WARD         3.0
3        JONES         4.0
4       MARTIN         5.0
5      unknown         3.0